parameters:
#    angular.example.class: Site\AngularBundle\Example

services:
#    angular.example:
#        class: %angular.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
