parameters:
#    front.example.class: Site\FrontBundle\Example
    front.controller.exception.class: Site\FrontBundle\Controller\ExceptionController

services:
#    front.example:
#        class: %front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    front.controller.exception:
        class: %front.controller.exception.class%
        arguments: [@twig, %kernel.debug%]
