parameters:
    front.controller.exception.class: Site\FrontBundle\Controller\ExceptionController

services:
    front.controller.exception:
        class: %front.controller.exception.class%
        arguments: ["@twig", %kernel.debug%]
        calls:
            - [ setContainer, ["@service_container"]]
