<?php

namespace Site\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends EntityRepository
{
}
