<?php

namespace Site\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasketMissingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketMissingRepository extends EntityRepository
{
}
