<?php

namespace Site\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemperatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemperatureRepository extends EntityRepository
{
}
