admin_homepage:
    pattern:  /admin
    defaults: { _controller: AdminBundle:Default:index }

users:
    resource: "@AdminBundle/Resources/config/routes/user.yml"

misc:
    resource: "@AdminBundle/Resources/config/routes/misc.yml"

animals:
    resource: "@AdminBundle/Resources/config/routes/animal.yml"

species:
    resource: "@AdminBundle/Resources/config/routes/species.yml"

product_types:
    resource: "@AdminBundle/Resources/config/routes/product-type.yml"

products:
    resource: "@AdminBundle/Resources/config/routes/product.yml"

basket_states:
    resource: "@AdminBundle/Resources/config/routes/basket-states.yml"
